In [5]:
from kaggle_environments import make, evaluate, utils

env = make("connectx")

dir(env)

['_Environment__agent_runner',
 '_Environment__get_shared_state',
 '_Environment__get_state',
 '_Environment__process_specification',
 '_Environment__run_interpreter',
 '_Environment__set_state',
 '_Environment__state_schema',
 '_Environment__state_schema_value',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__state_schema_0',
 '__state_schema_1',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'agents',
 'clone',
 'configuration',
 'debug',
 'debug_print',
 'done',
 'html_renderer',
 'id',
 'info',
 'interpreter',
 'logs',
 'name',
 'play',
 'pool',
 'render',
 'renderer',
 'reset',
 'run',
 'specification',
 'state',
 'step',
 'steps',
 'toJSON',
 

In [14]:
env.specification

{'name': 'connectx',
 'title': 'ConnectX',
 'description': 'Classic Connect in a row but configurable.',
 'version': '1.0.1',
 'agents': [2],
 'configuration': {'episodeSteps': {'description': 'Maximum number of steps in the episode.',
   'type': 'integer',
   'minimum': 1,
   'default': 1000},
  'actTimeout': {'description': 'Maximum runtime (seconds) to obtain an action from an agent.',
   'type': 'number',
   'minimum': 0,
   'default': 2},
  'runTimeout': {'description': 'Maximum runtime (seconds) of an episode (not necessarily DONE).',
   'type': 'number',
   'minimum': 0,
   'default': 1200},
  'columns': {'description': 'The number of columns on the board',
   'type': 'integer',
   'default': 7,
   'minimum': 1},
  'rows': {'description': 'The number of rows on the board',
   'type': 'integer',
   'default': 6,
   'minimum': 1},
  'inarow': {'description': 'The number of checkers in a row required to win.',
   'type': 'integer',
   'default': 4,
   'minimum': 1},
  'agentTimeout

In [15]:
env.specification.configuration.columns

{'description': 'The number of columns on the board',
 'type': 'integer',
 'default': 7,
 'minimum': 1}

In [7]:
env.state

[{'action': 0,
  'reward': 0,
  'info': {},
  'observation': {'remainingOverageTime': 60,
   'step': 0,
   'board': [0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0],
   'mark': 1},
  'status': 'ACTIVE'},
 {'action': 0,
  'reward': 0,
  'info': {},
  'observation': {'remainingOverageTime': 60, 'mark': 2},
  'status': 'INACTIVE'}]

In [8]:
env.step([0,1])

[{'action': 0,
  'reward': 0,
  'info': {},
  'observation': {'remainingOverageTime': 60,
   'step': 1,
   'board': [0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0],
   'mark': 1},
  'status': 'INACTIVE'},
 {'action': 1,
  'reward': 0,
  'info': {},
  'observation': {'remainingOverageTime': 60, 'mark': 2},
  'status': 'ACTIVE'}]

In [ ]:
import numpy as np


np.array(env.state[0]["observation"]["board"]).reshape((6,7))



1


In [13]:
print(env.state[0]["observation"]["mark"])
print(type(env.state[0]["observation"]["mark"]))

1
<class 'int'>


In [21]:
print(env.configuration.columns)
print(type(env.configuration))

7
<class 'kaggle_environments.utils.Struct'>


In [22]:
done = env.done
while not done:
    env.step([np.random.randint(0,7), np.random.randint(0,7)])
    done = env.done
print(env.state)

[{'action': 3, 'reward': 1, 'info': {}, 'observation': {'remainingOverageTime': 60, 'step': 13, 'board': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 2, 1, 2, 0, 0, 1, 0, 1, 1, 1, 1, 0, 2, 0], 'mark': 1}, 'status': 'DONE'}, {'action': 3, 'reward': -1, 'info': {}, 'observation': {'remainingOverageTime': 60, 'mark': 2}, 'status': 'DONE'}]


In [24]:
print(np.array(env.state[0]["observation"]["board"]).reshape((6,7)))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [2 0 1 0 0 2 0]
 [2 1 2 0 0 1 0]
 [1 1 1 1 0 2 0]]


In [25]:
print(env.state)

[{'action': 3, 'reward': 1, 'info': {}, 'observation': {'remainingOverageTime': 60, 'step': 13, 'board': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 2, 1, 2, 0, 0, 1, 0, 1, 1, 1, 1, 0, 2, 0], 'mark': 1}, 'status': 'DONE'}, {'action': 3, 'reward': -1, 'info': {}, 'observation': {'remainingOverageTime': 60, 'mark': 2}, 'status': 'DONE'}]


In [26]:
env.reset()
print(env.state[0])
env.step([0,7])
print(env.state[0])
env.step([1,6])
print(env.state[0])

{'action': 0, 'reward': 0, 'info': {}, 'observation': {'remainingOverageTime': 60, 'step': 0, 'board': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'mark': 1}, 'status': 'ACTIVE'}
{'action': 0, 'reward': 0, 'info': {}, 'observation': {'remainingOverageTime': 60, 'step': 1, 'board': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], 'mark': 1}, 'status': 'INACTIVE'}
{'action': 1, 'reward': 0, 'info': {}, 'observation': {'remainingOverageTime': 60, 'step': 2, 'board': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2], 'mark': 1}, 'status': 'ACTIVE'}


In [28]:
print(env.configuration.rows)

6
