In [5]:
from kaggle_environments import make, evaluate, utils

env = make("connectx")

dir(env)

['_Environment__agent_runner',
 '_Environment__get_shared_state',
 '_Environment__get_state',
 '_Environment__process_specification',
 '_Environment__run_interpreter',
 '_Environment__set_state',
 '_Environment__state_schema',
 '_Environment__state_schema_value',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__state_schema_0',
 '__state_schema_1',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'agents',
 'clone',
 'configuration',
 'debug',
 'debug_print',
 'done',
 'html_renderer',
 'id',
 'info',
 'interpreter',
 'logs',
 'name',
 'play',
 'pool',
 'render',
 'renderer',
 'reset',
 'run',
 'specification',
 'state',
 'step',
 'steps',
 'toJSON',
 

In [14]:
env.specification

{'name': 'connectx',
 'title': 'ConnectX',
 'description': 'Classic Connect in a row but configurable.',
 'version': '1.0.1',
 'agents': [2],
 'configuration': {'episodeSteps': {'description': 'Maximum number of steps in the episode.',
   'type': 'integer',
   'minimum': 1,
   'default': 1000},
  'actTimeout': {'description': 'Maximum runtime (seconds) to obtain an action from an agent.',
   'type': 'number',
   'minimum': 0,
   'default': 2},
  'runTimeout': {'description': 'Maximum runtime (seconds) of an episode (not necessarily DONE).',
   'type': 'number',
   'minimum': 0,
   'default': 1200},
  'columns': {'description': 'The number of columns on the board',
   'type': 'integer',
   'default': 7,
   'minimum': 1},
  'rows': {'description': 'The number of rows on the board',
   'type': 'integer',
   'default': 6,
   'minimum': 1},
  'inarow': {'description': 'The number of checkers in a row required to win.',
   'type': 'integer',
   'default': 4,
   'minimum': 1},
  'agentTimeout

In [15]:
env.specification.configuration.columns

{'description': 'The number of columns on the board',
 'type': 'integer',
 'default': 7,
 'minimum': 1}

In [7]:
env.state

[{'action': 0,
  'reward': 0,
  'info': {},
  'observation': {'remainingOverageTime': 60,
   'step': 0,
   'board': [0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0],
   'mark': 1},
  'status': 'ACTIVE'},
 {'action': 0,
  'reward': 0,
  'info': {},
  'observation': {'remainingOverageTime': 60, 'mark': 2},
  'status': 'INACTIVE'}]

In [8]:
env.step([0,1])

[{'action': 0,
  'reward': 0,
  'info': {},
  'observation': {'remainingOverageTime': 60,
   'step': 1,
   'board': [0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0],
   'mark': 1},
  'status': 'INACTIVE'},
 {'action': 1,
  'reward': 0,
  'info': {},
  'observation': {'remainingOverageTime': 60, 'mark': 2},
  'status': 'ACTIVE'}]

In [ ]:
import numpy as np


np.array(env.state[0]["observation"]["board"]).reshape((6,7))



1


In [13]:
print(env.state[0]["observation"]["mark"])
print(type(env.state[0]["observation"]["mark"]))

1
<class 'int'>


In [21]:
print(env.configuration.columns)
print(type(env.configuration))

7
<class 'kaggle_environments.utils.Struct'>


In [22]:
done = env.done
while not done:
    env.step([np.random.randint(0,7), np.random.randint(0,7)])
    done = env.done
print(env.state)

[{'action': 3, 'reward': 1, 'info': {}, 'observation': {'remainingOverageTime': 60, 'step': 13, 'board': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 2, 1, 2, 0, 0, 1, 0, 1, 1, 1, 1, 0, 2, 0], 'mark': 1}, 'status': 'DONE'}, {'action': 3, 'reward': -1, 'info': {}, 'observation': {'remainingOverageTime': 60, 'mark': 2}, 'status': 'DONE'}]


In [24]:
print(np.array(env.state[0]["observation"]["board"]).reshape((6,7)))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [2 0 1 0 0 2 0]
 [2 1 2 0 0 1 0]
 [1 1 1 1 0 2 0]]


In [25]:
print(env.state)

[{'action': 3, 'reward': 1, 'info': {}, 'observation': {'remainingOverageTime': 60, 'step': 13, 'board': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 2, 1, 2, 0, 0, 1, 0, 1, 1, 1, 1, 0, 2, 0], 'mark': 1}, 'status': 'DONE'}, {'action': 3, 'reward': -1, 'info': {}, 'observation': {'remainingOverageTime': 60, 'mark': 2}, 'status': 'DONE'}]


In [26]:
env.reset()
print(env.state[0])
env.step([0,7])
print(env.state[0])
env.step([1,6])
print(env.state[0])

{'action': 0, 'reward': 0, 'info': {}, 'observation': {'remainingOverageTime': 60, 'step': 0, 'board': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'mark': 1}, 'status': 'ACTIVE'}
{'action': 0, 'reward': 0, 'info': {}, 'observation': {'remainingOverageTime': 60, 'step': 1, 'board': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], 'mark': 1}, 'status': 'INACTIVE'}
{'action': 1, 'reward': 0, 'info': {}, 'observation': {'remainingOverageTime': 60, 'step': 2, 'board': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2], 'mark': 1}, 'status': 'ACTIVE'}


In [28]:
print(env.configuration.rows)

6


In [ ]:
from kaggle_environments import evaluate, make
import ConnectXNN as cxnn
from logger_setup import get_logger
import numpy as np
import torch

logger = get_logger("Test","Test.log")

model = cxnn.ConnectXNet()
model = cxnn.load_model(model,"./models","final_model.pth")

environment = "connectx"
configuration = {"rows": 6, "columns": 7, "inarow": 4}
steps = []

# This agent random chooses a non-empty column.
def my_agent(observation, configuration):
    mark = observation.mark
    row = configuration.rows
    col = configuration.columns
    
    board = np.array(observation.board).reshape(row, col)
    
    P1 = (board == 1).astype(np.float32)
    P2 = ((board == 2)).astype(np.float32)
    if mark == 2:
        player_plane = np.full((row, col), 1, dtype=np.float32)
    elif mark == 1:
        player_plane = np.full((row, col), -1, dtype=np.float32)
    
    input = torch.tensor(np.stack([P1, P2, player_plane])).unsqueeze(0)
    
    p_logits, v = model(input)
    p_logits = p_logits.detach().cpu().numpy().flatten()
    
    valid_actions = [c for c in range(col) if board[0][c] == 0]
    mask = np.full_like(p_logits, -np.inf)
    mask[valid_actions] = p_logits[valid_actions]
    
    # 필터링된 logits에 softmax 적용
    filtered_probs = np.exp(mask) / np.sum(np.exp(mask))
    
    action = np.random.choice(len(filtered_probs), p=filtered_probs)
    
        
    return action

# Which agents to run repeatedly.  Same as env.run(agents)
agents = ["random", my_agent]

# How many times to run them.
num_episodes = 10

rewards = evaluate(environment, agents, configuration, steps, num_episodes)

print(f"Rewards for random against random. {rewards}")
env = make("connectx", debug=True)
env.reset()
env.play([None,"random"])

Model is loaded in : ./models/final_model.pth
Rewards for random against random. [[-1, 1], [1, -1], [1, -1], [1, -1], [1, -1], [-1, 1], [1, -1], [1, -1], [1, -1], [-1, 1]]


In [ ]:
import train as tr
import ConnectXNN as cxnn
import numpy as np
import torch
from kaggle_environments import make, evaluate
import MCTS_Connectx as mcts

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model1 = cxnn.ConnectXNet()
model1 = cxnn.load_model(model1, './models/checkpoints', 'model_iter_5.pth', device=device)
model2 = cxnn.ConnectXNet()
model2 = cxnn.load_model(model2, './models/checkpoints', 'model_iter_100.pth', device=device)

model1.eval()
model2.eval()

def my_agent1(observation, configuration):
    mark = observation.mark
    row = configuration.rows
    col = configuration.columns
    
    board = np.array(observation.board).reshape(row, col)
    
    P1 = (board == 1).astype(np.float32)
    P2 = ((board == 2)).astype(np.float32)
    if mark == 2:
        player_plane = np.full((row, col), 1, dtype=np.float32)
    elif mark == 1:
        player_plane = np.full((row, col), -1, dtype=np.float32)
    
    input = torch.tensor(np.stack([P1, P2, player_plane])).unsqueeze(0).to(device)
    
    p_logits, v = model1(input)
    p_logits = p_logits.detach().cpu().numpy().flatten()
    
    valid_actions = [c for c in range(col) if board[0][c] == 0]
    mask = np.full_like(p_logits, -np.inf)
    mask[valid_actions] = p_logits[valid_actions]
    
    # 필터링된 logits에 softmax 적용
    filtered_probs = np.exp(mask) / np.sum(np.exp(mask))
    
    action = np.random.choice(len(filtered_probs), p=filtered_probs)
    
        
    return action

def my_agent2(observation, configuration):
    mark = observation.mark
    row = configuration.rows
    col = configuration.columns
    
    board = np.array(observation.board).reshape(row, col)
    
    P1 = (board == 1).astype(np.float32)
    P2 = ((board == 2)).astype(np.float32)
    if mark == 2:
        player_plane = np.full((row, col), 1, dtype=np.float32)
    elif mark == 1:
        player_plane = np.full((row, col), -1, dtype=np.float32)
    
    input = torch.tensor(np.stack([P1, P2, player_plane])).unsqueeze(0).to(device)
    
    p_logits, v = model2(input)
    p_logits = p_logits.detach().cpu().numpy().flatten()
    
    valid_actions = [c for c in range(col) if board[0][c] == 0]
    mask = np.full_like(p_logits, -np.inf)
    mask[valid_actions] = p_logits[valid_actions]
    
    # 필터링된 logits에 softmax 적용
    filtered_probs = np.exp(mask) / np.sum(np.exp(mask))
    
    action = np.random.choice(len(filtered_probs), p=filtered_probs)
    
        
    return action

if __name__ == "__main__":
    env = make("connectx", debug=True)
    env.reset()
    env.run([my_agent2, "negamax"])
    print("Game finished.")
    print(env.render(mode="ipython"))

c:\Users\LTY\Documents\GitHub\connectx-lty\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
INFO: Model state_dict loaded from: ./models/checkpoints\model_iter_5.pth onto device cuda
INFO: Model state_dict loaded from: ./models/checkpoints\model_iter_100.pth onto device cuda


Game finished.


None


In [8]:
from kaggle_environments import evaluate

# Same definitions as "make" above.
environment = "connectx"
configuration = {"rows": 7, "columns": 6, "inarow": 4}
steps = []

# Which agents to run repeatedly.  Same as env.run(agents)
agents = [my_agent2, "random"]

# How many times to run them.
num_episodes = 400

rewards = evaluate(environment, agents, configuration, steps, num_episodes)

p1_wins = [x[0] for x in rewards if x[0] > x[1]]
p2_wins = [x[1] for x in rewards if x[0] < x[1]]

print(sum(p1_wins), len(p1_wins))
print(sum(p2_wins), len(p2_wins))

KeyboardInterrupt: 

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 설정
num_actions = 7
num_samples = 1000
alpha_values = [0.1, 0.3, 0.6, 1.0, 3.0, 10.0]

# 샘플 수집
samples_dict = {}
for alpha in alpha_values:
    dirichlet_samples = np.random.dirichlet([alpha] * num_actions)
    print(f"Alpha: {alpha}, Samples: {dirichlet_samples}")
    


Alpha: 0.1, Samples: [8.01770593e-04 5.51959599e-01 3.38389577e-01 5.08058204e-03
 1.03768472e-01 1.38924467e-12 1.03550752e-15]
Alpha: 0.3, Samples: [3.23946892e-01 2.18964819e-02 2.89011130e-05 3.19734378e-01
 1.48020259e-04 2.49001276e-02 3.09345199e-01]
Alpha: 0.6, Samples: [0.05650126 0.38936923 0.08000109 0.03184837 0.0793507  0.06442004
 0.29850931]
Alpha: 1.0, Samples: [0.23483427 0.005234   0.11343342 0.08835263 0.01792026 0.1375029
 0.40272252]
Alpha: 3.0, Samples: [0.25758421 0.19870013 0.10106855 0.14468717 0.06227741 0.09347437
 0.14220817]
Alpha: 10.0, Samples: [0.1628623  0.17725452 0.12405716 0.15300899 0.08302193 0.1099547
 0.18984041]


In [11]:
import train as tr
import ConnectXNN as cxnn
import numpy as np
import torch
from kaggle_environments import make, evaluate
import MCTS_v2 as mcts

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model1 = cxnn.ConnectXNet()
model1 = cxnn.load_model(model1, './models/checkpoints', 'model_iter_5.pth', device=device)
model2 = cxnn.ConnectXNet()
model2 = cxnn.load_model(model2, './models/checkpoints', 'model_iter_100.pth', device=device)

model1.eval()
model2.eval()



def my_agent1(observation, configuration):
    mark = observation.mark
    row = configuration.rows
    col = configuration.columns
    
    board = np.array(observation.board).reshape(row, col)
    
    P1 = (board == 1).astype(np.float32)
    P2 = ((board == 2)).astype(np.float32)
    if mark == 2:
        player_plane = np.full((row, col), 1, dtype=np.float32)
    elif mark == 1:
        player_plane = np.full((row, col), -1, dtype=np.float32)
    
    action, _ = mcts.select_mcts_action(initial_board=board, initial_player_to_act=mark, config=configuration,
                       model=model1, n_simulations = 50 , c_puct = 0, c_fpu=0, device =device,
                       np_rng=np.random.default_rng(), dirichlet_alpha=0, dirichlet_epsilon=0,
                       temperature=0.0, log_debug=False)
    
        
    return action

def my_agent2(observation, configuration):
    mark = observation.mark
    row = configuration.rows
    col = configuration.columns
    
    board = np.array(observation.board).reshape(row, col)
    
    P1 = (board == 1).astype(np.float32)
    P2 = ((board == 2)).astype(np.float32)
    if mark == 2:
        player_plane = np.full((row, col), 1, dtype=np.float32)
    elif mark == 1:
        player_plane = np.full((row, col), -1, dtype=np.float32)
    
    action, _ = mcts.select_mcts_action(initial_board=board, initial_player_to_act=mark, config=configuration,
                       model=model2, n_simulations = 100 , c_puct = 0, c_fpu=0, device =device,
                       np_rng=np.random.default_rng(), dirichlet_alpha=0, dirichlet_epsilon=0,
                       temperature=0.0, log_debug=False)
    
        
    return action

if __name__ == "__main__":
    env = make("connectx", debug=True)
    env.reset()
    env.run([my_agent2, "negamax"])
    print("Game finished.")
    print(env.render(mode="ipython"))

INFO: Model state_dict loaded from: ./models/checkpoints\model_iter_5.pth onto device cuda
INFO: Model state_dict loaded from: ./models/checkpoints\model_iter_100.pth onto device cuda


Game finished.


None
